#!/usr/bin/bash
#
# Copyright (c) 2020 Anthony J. Greenberg
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Set the backlight. Adding the user to the video group (via udev rules) to use this script without sudo.
#

#
# $1 should have A for add and S for subtract; $2 will have the percentage of max_brightness
#

max=$( cat /sys/class/backlight/intel_backlight/max_brightness )
val=$2
(( val=max*val/100 ))
outVal=$( cat /sys/class/backlight/intel_backlight/brightness )
case "$1" in
	A)
		(( outVal=outVal+val ))
		echo "$outVal" > /sys/class/backlight/intel_backlight/brightness
		;;
	S)
		(( outVal=outVal-val ))
		if (( outVal >= 0 )); then
			echo "$outVal" > /sys/class/backlight/intel_backlight/brightness
		else
			echo "0" > /sys/class/backlight/intel_backlight/brightness
		fi
		;;
	*)
		echo "Usage: changeBacklight [AS] NUM"
		;;
esac

