#!/usr/bin/bash

#
# Check for new e-mail messages. They are fetched in the background by imapSync
#

numMess=$( find $HOME/.mail -type d -name Inbox -exec ls {}/new ';' | wc -w )

if [ $numMess == 1 ]; then
	echo -en "$numMess message"
elif [ $numMess > 1 ]; then
    echo -en "$numMess messages"
else
    echo "no new mail"
fi

