#!/usr/bin/bash

#while true; do
#	curTime=$( date '+%a %b %e %R %Z' )
#	sleep 20s
#done

while true; do
	curTime=$( date '+%a %b %e %R %Z' )
	curBat=$( $HOME/.scripts/battery )
	curCPU=$( $HOME/.scripts/cpuUsage )
	curCPUtemp=$( $HOME/.scripts/cpuTemp )
	curGPU=$( $HOME/.scripts/gpuUsage )
	curGPUtemp=$( $HOME/.scripts/gpuTemp )
	curMem=$( $HOME/.scripts/memory )
	curDisk=$( $HOME/.scripts/disk )
	curMail=$( $HOME/.scripts/checkMail )
	curPM=$( $HOME/.scripts/pacupdate )
	curVol=$( $HOME/.scripts/getVolume )
	curWiFi=$( $HOME/.scripts/wifiSignal )
	xsetroot -name " $curMail $curPM  $curVol  $curWiFi ;$curTime | $curBat | $curCPU $curCPUtemp | $curGPU $curGPUtemp | $curMem | $curDisk |  $( cat $HOME/systemConf/my_ip )"
	sleep 10s
done

