#!/usr/bin/bash

#
# Sync the IMAP mailboxes and check how many new messages are there
#
while true; do
	if nmcli networking connectivity | grep -q 'full'; then
		mbsync -aqq > /dev/null 2>&1
	fi
	sleep 5m
done

