#!/usr/bin/bash

#
# Tests if there is a monitor connected with HDMI and turns it on
#
if xrandr | grep HDMI | grep -wq connected; then 
	port=$( xrandr | grep HDMI | grep -w connected | cut -d ' ' -f1 )
	dpID=$( xrandr | grep DP | grep -w connected | cut -d ' ' -f1)
	xrandr --output $port --auto --left-of $dpID
fi

