#!/usr/bin/bash
#
# Copyright (c) 2020 Anthony J. Greenberg
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Increase/decrease mic volume or mute
#

pctlHeadAvail=$( pactl list sources | grep 'Mic2: Headphones Stereo Microphone' | cut -d ',' -f3 )
if [[ $pctlHeadAvail = " not available)" ]]; then
	sourceID=$( pactl list sources | grep -B 1 'Description: Comet Lake PCH cAVS Digital Microphone' | head -1 | awk '{print $2}' )
else
	sourceID=$( pactl list sources | grep -B 1 'Description: Comet Lake PCH cAVS Headphones Stereo Microphone' | head -1 | awk '{print $2}' )
fi
if [[ $1 -eq 0 ]] || [[ -z "$1" ]]; then
	pactl set-source-mute $sourceID toggle && pkill --signal RTMIN+12 -x dwmbar
else
	pactl set-source-volume $sourceID ${1}% && pkill --signal RTMIN+12 -x dwmbar
fi
