#!/usr/bin/env bash

#
# Run this instead of vifm to get image/pdf previews. Taken from https://gitlab.com/dwt1/dotfiles
#

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"
# ueberzug is in this direcotry; make sure it is in the path
export PATH=$PATH:$HOME/.local/bin

function cleanup {
    rm "$FIFO_UEBERZUG" 2>/dev/null
    pkill -P $$ 2>/dev/null
}

rm "$FIFO_UEBERZUG" 2>/dev/null
mkfifo "$FIFO_UEBERZUG"
trap cleanup EXIT
tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &

vifm
cleanup
